update=05.05.2017 15:49:53
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[schematic_editor]
version=1
PageLayoutDescrFile=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/std.kicad_wks
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/ACS
LibName31=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/ADV7533
LibName32=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/bluetooth
LibName33=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/camera1
LibName34=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/CC26XX
LibName35=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/con-usb
LibName36=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/ESP8266 - Kopie
LibName37=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/ESP8266
LibName38=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/ESS
LibName39=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/LMH0030
LibName40=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/lora
LibName41=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/open-project
LibName42=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/power
LibName43=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/s_relays
LibName44=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/shield_arduino
LibName45=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/silego
LibName46=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/siona
LibName47=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/STM
LibName48=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/stm8
LibName49=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/stm32
LibName50=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/TFP410
LibName51=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/TI
LibName52=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/top22xy
LibName53=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/TRANSFORMER
LibName54=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/USB_c
LibName55=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/w_analog
LibName56=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/w_connectors
LibName57=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/w_device
LibName58=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/w_logic
LibName59=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/w_memory
LibName60=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/w_microcontrollers
LibName61=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/w_opto
LibName62=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/w_relay
LibName63=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/w_rtx
LibName64=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/w_transistor
LibName65=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/w_vacuum
LibName66=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/IMX7D
LibName67=H:/GEE/Extern/Elektronik_allg/EAGLE Projekte/KiCad/LIBS/voltages
